version: "3.8"

services:
  api:
    image: api:latest
    volumes:
      - ../..:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    command: sh -c "npm install && npm run start:dev"
    environment:
      DATABASE_HOST: ${DATABASE_HOST_DEV}
      DATABASE_PORT: ${DATABASE_PORT_DEV}
      DATABASE_USER: ${DATABASE_USER_DEV}
      DATABASE_PSWD: ${DATABASE_PSWD_DEV}
      DATABASE_NAME: ${DATABASE_NAME}
      NODE_ENV: development
      RABBITMQ_URL: ${RABBITMQ_URL_DEV}

    depends_on:
      mysql_db_dev_service:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    stdin_open: true
    tty: true
    restart: no
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"

  mysql_db_dev_service:
    image: mysql:8.0
    container_name: mysql_db_dev
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PSWD_DEV}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3307:3306
    volumes:
      - mysql-data-dev:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 5s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  rabbitmq:
    image: rabbitmq:3.11-management
    hostname: rabbitmq
    container_name: rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER_DEV}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PSWD_DEV}
    ports:
      - "5672:5672" # Porta diferente para dev se quiser
      - "15673:15672" # Painel dev
    volumes:
      - rabbitmq-dev-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql-data-dev:
  rabbitmq-dev-data:
